version: "3.9"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: api_sexshop
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data
    ports:
      -  ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

