export type CreateCustomer = {
    name: string,
    cpfCnpj: string,
    email?: string,
    phone?: string,
    mobilePhone?: string,
    address?: string,
    addressNumber?: string,
    complement?: string | null,
    province?: string,
    postalCode?: string,
    additionalEmails?: string,
    externalReference?: string,
    notificationDisabled?: boolean,
    observations?: string,
    city?: string,
    cityName?: string,
    state?: string,
    country?: string,
    stateInscription?: string,
    municipalInscription?: string,
    groupName?: string,
    company?: string
}